refactor vehicleGen to be more Pythonic
Stewart86/roadtaxTracker pull request #11
Opened 2019-10-02 14:57 UTC by Bezmehrabi

2019-10-03 18:14 UTC, MythreyaK commented on vehicleGen.py
> +    number = str(gen_num1 + gen_num2 + gen_num3 + gen_num4)
That's incorrect. What you're doing is adding up the numbers, `3`, `4`, `5`, `6` into `18` and returning that. The `str` for each of them is required to gat a string `3456`.

2019-10-03 18:15 UTC, MythreyaK commented on vehicleGen.py
> +    number = str(gen_num1 + gen_num2 + gen_num3 + gen_num4)
Same here

2019-10-03 18:18 UTC, MythreyaK requested changes
Please have a look at the comments

2019-10-17 02:53 UTC, merged

2019-10-17 02:53 UTC, Stewart86 commented
thank you!